include $(APPDIR)/Make.defs

PROGNAME  = ew
PRIORITY  = 100
STACKSIZE = 98304
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_313_EDGE_WALKER)

MAINSRC = ew_main.c
CSRCS   = alert_output.c alert_lcd.c alert_buzzer.c ew_ld2451.c ew_wifi_at.c ew_wifi_ui.c ew_llm.c ew_chat.c ew_pinyin.c ew_agent.c ew_agent_tool.c ew_serial_ctl.c ew_mirror.c

include $(APPDIR)/Application.mk
