include $(APPDIR)/Make.defs

PROGNAME  = ew
PRIORITY  = 100
STACKSIZE = 65536
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_313_EDGE_WALKER)

MAINSRC = ew_main.c
CSRCS   = alert_output.c alert_lcd.c alert_buzzer.c ew_ld2451.c ew_wifi_at.c

include $(APPDIR)/Application.mk
