include $(APPDIR)/Make.defs

PROGNAME  = ew
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_313_EDGE_WALKER)

MAINSRC = ew_main.c
CSRCS   = alert_output.c alert_lcd.c ew_ld2451.c

include $(APPDIR)/Application.mk
